### ISSUE TITLE
font display is broken

### ISSUE THREAD

**Issue by lamalunderscore** [lu0/rofi-blurry-powermenu#9]
I am trying to get this template to run on arch, so I already had to specify the display width and height manually. But that works fine.

When I run the .sh, the glyphs do not actually take the text color, but stay black and have a white chunky background. I tried using different fonts, but that indeed does only change the glyph.

Did you encounter something like this during development?
![powermenu](https://github.com/lu0/rofi-blurry-powermenu/assets/84677812/ae9f6d4f-5533-4ba9-8447-c69096d478a0)

**Comment by lu0** [comment]
Hi @lamalunderscore, are you still facing this issue in Arch?

**Comment by lamalunderscore** [comment]
Hi @lu0, yes I was still facing part of this issue when I was starting to write this. The state I was at was to have a transparent background for the icons, but there still was the white part left of the bar that you can see on my screenshot. I had hit the pause button back then and just left it to be a matter of another day. Today I then saw, that somehow I broke the font again (probably a decision back then, but I honestly don't remember). 
I rewrote the following part four times because I was still testing in between, lol.

It seems to have been a problem with generalization. I believe this to be a final list of issues I had, besides the margins:

- Rofi did not use your custom feather font, so the Unicode characters were pointing to something else
- The text background was white instead of transparent
- the icon background was white instead of transparent

All of that was fixed by introducing the `element-text{}` box to the theme config:
`element-text{
background-color: transparent;
text-color: inherit;
font: "feather-custom-char-map 42";`, and setting "show-icons" to false. I could have probably also introduced `element-icons` or something, but I did not bother and just turned them off instead. It is important to specify a font size, otherwise, rofi does not accept the setting and defaults to the WeblySleek font.

So now, I do not have this issue anymore. I can get on to finding the right margins for my screen. The margins set by you were absolutely not fitting for me. I guess that's an issue of the padding changes from 1.5.4 to 1.6
